# Generated by Django 4.1.3 on 2022-11-25 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('messages', models.TextField()),
                ('date_message', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
